# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EMeUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnaMenu(object):
    def setupUi(self, AnaMenu):
        AnaMenu.setObjectName("AnaMenu")
        AnaMenu.resize(1300, 820)
        AnaMenu.setMinimumSize(QtCore.QSize(1300, 820))
        AnaMenu.setMaximumSize(QtCore.QSize(1300, 820))
        self.pushButton_Basla = QtWidgets.QPushButton(AnaMenu)
        self.pushButton_Basla.setEnabled(False)
        self.pushButton_Basla.setGeometry(QtCore.QRect(830, 740, 461, 71))
        self.pushButton_Basla.setObjectName("pushButton_Basla")
        self.pushButton_KameraAc = QtWidgets.QPushButton(AnaMenu)
        self.pushButton_KameraAc.setGeometry(QtCore.QRect(9, 741, 371, 31))
        self.pushButton_KameraAc.setObjectName("pushButton_KameraAc")
        self.pushButton_MedyaSec = QtWidgets.QPushButton(AnaMenu)
        self.pushButton_MedyaSec.setGeometry(QtCore.QRect(9, 780, 371, 31))
        self.pushButton_MedyaSec.setObjectName("pushButton_MedyaSec")
        self.pushButton_WhiteListEdit = QtWidgets.QPushButton(AnaMenu)
        self.pushButton_WhiteListEdit.setGeometry(QtCore.QRect(390, 740, 211, 71))
        self.pushButton_WhiteListEdit.setObjectName("pushButton_WhiteListEdit")
        self.pushButton_Model_Egit = QtWidgets.QPushButton(AnaMenu)
        self.pushButton_Model_Egit.setEnabled(True)
        self.pushButton_Model_Egit.setGeometry(QtCore.QRect(610, 740, 211, 71))
        self.pushButton_Model_Egit.setObjectName("pushButton_Model_Egit")
        self.Ekran = QtWidgets.QLabel(AnaMenu)
        self.Ekran.setGeometry(QtCore.QRect(10, 10, 1280, 720))
        self.Ekran.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Ekran.setText("")
        self.Ekran.setObjectName("Ekran")

        self.retranslateUi(AnaMenu)
        QtCore.QMetaObject.connectSlotsByName(AnaMenu)

    def retranslateUi(self, AnaMenu):
        _translate = QtCore.QCoreApplication.translate
        AnaMenu.setWindowTitle(_translate("AnaMenu", "ExceptMe"))
        self.pushButton_Basla.setText(_translate("AnaMenu", "Başlat"))
        self.pushButton_KameraAc.setText(_translate("AnaMenu", "Kameraya Aç"))
        self.pushButton_MedyaSec.setToolTip(_translate("AnaMenu", "İstenilen medyayı seçiniz."))
        self.pushButton_MedyaSec.setText(_translate("AnaMenu", "Resim/Video Seç"))
        self.pushButton_WhiteListEdit.setToolTip(_translate("AnaMenu", "Eklemek istediğiniz kişinin resmini dosyaya bırakınız.(Birden fazla tavsiye edilir.)"))
        self.pushButton_WhiteListEdit.setText(_translate("AnaMenu", "WhiteList Ekle/Çıkar"))
        self.pushButton_Model_Egit.setText(_translate("AnaMenu", "Modeli Eğit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AnaMenu = QtWidgets.QWidget()
    ui = Ui_AnaMenu()
    ui.setupUi(AnaMenu)
    AnaMenu.show()
    sys.exit(app.exec_())
